app/blueprints/auth.py
from functools import wraps

from flask import flash, redirect, url_for, render_template, Blueprint
from flask_login import login_user, LoginManager, current_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash

from ..models.models import User, Role, db
from ..forms.forms import RegisterForm, LoginForm

login_manager = LoginManager()
auth_blueprint = Blueprint('auth', __name__, template_folder = 'templates')

def redirect_unauthorized():
    flash('Registrate antes de acceder a la pagina !!')
    return redirect(url_for('auth.login'))

@login_manager.unauthorized_handler
def unauthorized():
    return redirect_unauthorized()

# Create a user_loader callback
@login_manager.user_loader
def load_user(user_id):
    return db.get_or_404(User, user_id)

def permission_required(permission):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            # Get the user's role from the database
            role = Role.query.filter_by(id=current_user.role_id).first()

            # Check if the role has the required permission
            if not getattr(role, permission):
                flash('No tienes permisos para ver esta pagina.')
                return redirect(url_for('auth.login'))
            return f(*args, **kwargs)
        return decorated_function
    return decorator

## User operations
@auth_blueprint.route('/register', methods = ['GET', 'POST'])
# @permission_required('can_create_users')
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        
        name = form.name.data
        email = form.email.data
        password = form.password.data
        user = db.session.execute(db.select(User).where(User.email == email)).scalar()
        if user:
            flash('Ese email ya existe porfavor inicia sesion.')
            return redirect(url_for('auth.login'))

        user_role = db.session.execute(db.select(Role).where(Role.role_title == 'user')).scalar()
     
        # If user role does not exist, create it
        if not user_role:
            user_role = Role(
                role_title = 'user',
                role_description = 'Default role for new users',
                can_view_bills = True,
                can_create_bills = True
            )
            db.session.add(user_role)
            db.session.commit()

        # Use Werkzeug to hash the user's password when creating a new user.
        hash_password = generate_password_hash(password=password, method='pbkdf2:sha256', salt_length=8) 
        new_user = User(
            name = name,
            email = email,
            password = hash_password,
            role = user_role
        )
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        return redirect(url_for('bills.get_all'))
    return render_template("register.html", form = form)


@auth_blueprint.route('/login', methods = ['GET', 'POST'])
def login(): 
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        # requested_user = db.get_or_404(User, post_id)

        # Retrieve a user from the database based on their email. 
        user = db.session.execute(db.select(User).where(User.email == email)).scalar()
        if user:
            if check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('bills.get_all'))
            flash('Contraseña incorrecta, porfavor intenta de nuevo.')
        else:
            flash('Ese email no esta registrado, porfavor intenta de nuevo!!')
    return render_template("login.html", form = form)

@auth_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

app/blueprints/create_db.py
from flask import Blueprint, redirect, render_template, url_for
from werkzeug.security import generate_password_hash, check_password_hash

import app
from ..forms.forms import FillDatabaseForm
from ..models.models import Role, User, test_db_integrity
from ..extensions import db


db_blueprint = Blueprint('db', __name__, template_folder = 'templates')

@db_blueprint.route('/create-db', methods = ['GET', 'POST'])
def create_db():
    form = FillDatabaseForm()
    if test_db_integrity():
        return redirect(url_for('auth.login'))
    
    if form.validate_on_submit():

        new_role = Role(
            role_title = 'admin',
            role_description = 'Administrator with full permissions',
            can_view_users = True,
            can_edit_users = True,
            can_delete_users = True,
            can_create_users = True,
            can_view_bills = True,
            can_edit_bills = True,
            can_delete_bills = True,
            can_create_bills = True,
            can_view_tags = True,
            can_edit_tags = True,
            can_delete_tags = True,
            can_create_tags = True,
            can_view_roles = True,
            can_edit_roles = True,
            can_delete_roles = True,
            can_create_roles = True,
            can_manage_document_types = True
        )
        db.session.add(new_role)
        db.session.flush()
        
        hash_password = generate_password_hash(password=form.password.data, method='pbkdf2:sha256', salt_length=8) 
        new_user = User(
            name = form.username.data,
            email = form.email.data,
            password = hash_password,
            role = new_role
        )
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('auth.login'))

    return render_template("create-db.html", form = form)

app/blueprints/doc_types.py
from flask import Blueprint, render_template, abort, url_for, redirect, flash, request, send_from_directory
from jinja2 import TemplateNotFound

from ..models.models import DocumentType, db
from ..forms.forms import  DocumentTypeForm
from .auth import login_required, permission_required

doc_types_blueprint = Blueprint('doc_types', __name__, template_folder = 'templates')

# Operations for document_types
@doc_types_blueprint.route('/', methods = ['GET', 'POST'])
@login_required
@permission_required('can_manage_document_types')
def get_post_document_types():
    form = DocumentTypeForm()
    if request.method == 'POST':
        new_tag = DocumentType( name = form.name.data )

        db.session.add(new_tag)
        db.session.commit()

    result = db.session.execute(db.select(DocumentType).where(DocumentType.is_active))
    document_type = result.scalars().all()

    # Se necesita otro template para cada vista tag y type
    return render_template('type-manager.html', form = form, items = document_type)

@doc_types_blueprint.route("/delete/<int:type_id>")
@login_required
@permission_required('can_manage_document_types')
def delete_document_type(type_id):
    type_to_delete = db.get_or_404(DocumentType, type_id)

    # db.session.delete(tag_to_delete)
    # Manage soft deletion
    type_to_delete.is_active = False
    db.session.commit()
    return redirect(url_for('doc_types.get_post_document_types'))

app/blueprints/roles.py
from flask import Blueprint, render_template, abort, url_for, redirect, flash
from jinja2 import TemplateNotFound
from sqlalchemy import and_

from ..models.models import Role, db
from ..forms.forms import CreateRoleForm
from .auth import login_required, permission_required

roles_blueprint = Blueprint('roles', __name__, template_folder = 'templates')

## Roles operations
@roles_blueprint.route('/', methods = ['GET', 'POST'])
@login_required
@permission_required('can_view_roles')
def roles_panel():
    result = db.session.execute(db.select(Role).where(Role.is_active != False))
    roles = result.scalars().all()
    return render_template('roles.html', all_roles = roles)

@roles_blueprint.route('/delete/<int:role_id>')
@login_required
@permission_required('can_delete_roles')
def delete_role(role_id):
    role_to_delete = db.get_or_404(Role, role_id)
    
    # Make a soft deletion
    role_to_delete.is_active = False
    # db.session.delete(role_to_delete)
    db.session.commit()
    return redirect(url_for('roles.roles_panel'))

@roles_blueprint.route('/create', methods = ['GET', 'POST'])
@permission_required('can_create_roles')
def create_role():
    form = CreateRoleForm()
    if form.validate_on_submit():
        role = db.session.execute(db.select(Role).where(and_(Role.role_title == form.role_title.data, Role.is_active != False))).scalar()

        if role:
            flash('Ese nombre de rol ya existe por favor ingresa otro.')
            return redirect(url_for('roles_panel'))
         
        new_role = Role(
            role_title = form.role_title.data,
            role_description = form.role_description.data,
            can_view_users = form.can_view_users.data,
            can_edit_users = form.can_edit_users.data,
            can_delete_users = form.can_delete_users.data,
            can_create_users = form.can_create_users.data,
            can_view_bills = form.can_view_bills.data,
            can_edit_bills = form.can_edit_bills.data,
            can_delete_bills = form.can_delete_bills.data,
            can_create_bills = form.can_create_bills.data,
            can_view_tags = form.can_view_tags.data,
            can_edit_tags = form.can_edit_tags.data,
            can_delete_tags = form.can_delete_tags.data,
            can_create_tags = form.can_create_tags.data,
            can_view_roles = form.can_view_roles.data,
            can_edit_roles = form.can_edit_roles.data,
            can_delete_roles = form.can_delete_roles.data,
            can_create_roles = form.can_create_roles.data,
            can_manage_document_types = form.can_manage_document_types.data,
            is_active = True
        )
        db.session.add(new_role)
        db.session.commit()
        
        return redirect(url_for('roles.roles_panel'))
    return render_template("register-role.html", form = form)

@roles_blueprint.route('/edit/<int:role_id>', methods = ['GET', 'POST'])
@login_required
@permission_required('can_edit_roles')
def edit_role(role_id):
    # Get the role from the database
    role = db.session.query(Role).filter_by(id=role_id).first()

    # Create a form with the data from the role
    edit_role_form = CreateRoleForm(
        role_title = role.role_title,
        role_description = role.role_description,
        can_view_users = role.can_view_users,
        can_edit_users = role.can_edit_users,
        can_delete_users = role.can_delete_users,
        can_create_users = role.can_create_users,
        can_view_bills = role.can_view_bills,
        can_edit_bills = role.can_edit_bills,
        can_delete_bills = role.can_delete_bills,
        can_create_bills = role.can_create_bills,
        can_view_tags = role.can_view_tags,
        can_edit_tags = role.can_edit_tags,
        can_delete_tags = role.can_delete_tags,
        can_create_tags = role.can_create_tags,
        can_view_roles = role.can_view_roles,
        can_edit_roles = role.can_edit_roles,
        can_delete_roles = role.can_delete_roles,
        can_create_roles = role.can_create_roles,
        can_manage_document_types = role.can_manage_document_types
    )

    if edit_role_form.validate_on_submit():
        role.role_title = edit_role_form.role_title.data
        role.role_description = edit_role_form.role_description.data

        role.can_view_users = edit_role_form.can_view_users.data
        role.can_edit_users = edit_role_form.can_edit_users.data
        role.can_delete_users = edit_role_form.can_delete_users.data
        role.can_create_users = edit_role_form.can_create_users.data

        role.can_view_bills = edit_role_form.can_view_bills.data
        role.can_edit_bills = edit_role_form.can_edit_bills.data
        role.can_delete_bills = edit_role_form.can_delete_bills.data
        role.can_create_bills = edit_role_form.can_create_bills.data

        role.can_view_tags = edit_role_form.can_view_tags.data
        role.can_edit_tags = edit_role_form.can_edit_tags.data
        role.can_delete_tags = edit_role_form.can_delete_tags.data
        role.can_create_tags = edit_role_form.can_create_tags.data

        role.can_view_roles = edit_role_form.can_view_roles.data
        role.can_edit_roles = edit_role_form.can_edit_roles.data
        role.can_delete_roles = edit_role_form.can_delete_roles.data
        role.can_create_roles = edit_role_form.can_create_roles.data
        role.can_manage_document_types = edit_role_form.can_manage_document_types.data
        
        db.session.commit()
        return redirect(url_for("roles.roles_panel"))
    return render_template("register-role.html", form = edit_role_form)

app/blueprints/tags.py
from flask import Blueprint, render_template, abort, url_for, redirect, flash, request, send_from_directory
from jinja2 import TemplateNotFound

from ..models.models import Tag, db
from ..forms.forms import  TagForm
from .auth import login_required, permission_required

tags_blueprint = Blueprint('tags', __name__, template_folder = 'templates')

# Operations for tags and types
@tags_blueprint.route('/', methods = ['GET', 'POST'])
@login_required
@permission_required('can_view_tags')
@permission_required('can_create_tags')
def get_post_tag():
    form = TagForm()
    if request.method == 'POST':
        new_tag = Tag( name = form.name.data, is_active = True )
    
        db.session.add(new_tag)
        db.session.commit()

    result = db.session.execute(db.select(Tag).where(Tag.is_active!=False))
    tags = result.scalars().all()
    return render_template('tag-manager.html', form = form, items = tags)

@tags_blueprint.route("/delete/<int:tag_id>")
@login_required
@permission_required('can_delete_tags')
def delete(tag_id):
    tag_to_delete = db.get_or_404(Tag, tag_id)
    tag_to_delete.is_active = False
    # db.session.delete(tag_to_delete)
    db.session.commit()
    return redirect(url_for('tags.get_post_tag'))

app/blueprints/users.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from jinja2 import TemplateNotFound
from werkzeug.security import generate_password_hash

from .auth import login_required, permission_required
from ..models.models import User, Role, db
from ..forms.forms import RegisterForm

users_blueprint = Blueprint('users', __name__, template_folder = 'templates')

@users_blueprint.route('/changue-role/<int:user_id>', methods = ['GET', 'POST'])
@login_required
@permission_required('can_edit_users')
def changue_role(user_id):

    # Get the user in order to edit its properties
    user = db.get_or_404(User, user_id)

    # Get all the roles available
    result = db.session.execute(db.select(Role).where(Role.is_active))
    roles = result.scalars().all()
    if request.method == 'POST':
        # Role selected by the user
        role_selected = request.form.get('user_role')
        
        user.role = db.get_or_404(Role, role_selected)
        db.session.commit()
        return redirect(url_for('users.users_panel'))
    
    return render_template('edit-user-role.html', roles = roles, user=user)
    
 
@users_blueprint.route('/')
@login_required
@permission_required('can_view_users')
def users_panel():
    result = db.session.execute(db.select(User))
    users = result.scalars().all()
    return render_template('users.html', all_users = users)

@users_blueprint.route('/edit/<int:user_id>', methods = ['GET', 'POST'])
@login_required
@permission_required('can_edit_users')
def edit_user(user_id):
    user = db.get_or_404(User, user_id)
    edit_form = RegisterForm(
        name = user.name,
        email = user.email
    )
    if edit_form.validate_on_submit():
        user.name = edit_form.name.data
        user.email = edit_form.email.data
        
        user.password = generate_password_hash(password=edit_form.password.data, method='pbkdf2:sha256', salt_length=8) 
        db.session.commit()
        return redirect(url_for("users.users_panel"))
    return render_template("register.html", form=edit_form)

@users_blueprint.route('/delete/<int:user_id>')
@login_required
@permission_required('can_delete_users')
def delete_user(user_id):
    user_to_delete = db.get_or_404(User, user_id)
    db.session.delete(user_to_delete)
    db.session.commit()
    flash('User removed')
    return redirect(url_for('users.users_panel'))

app/templates/create-db.html
{% from "bootstrap5/form.html" import render_form %} {% block content %}
{%include "header.html" %}

<main class="mb-4 mt-5 pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <p class="flash">{{ message }}</p>
        {% endfor %}
        {% endif %}
        {% endwith %}
        
        <!-- Title and Explanation -->
        <h1>Base de Datos No Encontrada</h1>
        <p class="lead">Parece que no existe una base de datos configurada o no hay un usuario administrador asociado. Por favor, complete el formulario a continuación para crear y configurar una nueva base de datos con un usuario administrador.</p>
        
        <!-- Form -->
        {{render_form(form)}}
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %} {% endblock %}

app/templates/edit-user-role.html
{% include "header.html" %}

<!-- Page Header -->
<main class="mb-4 mt-5 pt-5 ">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
              <p class="flash">{{ message }}</p>
            {% endfor %}
          {% endif %}
        {% endwith %}

        <form action="{{url_for('users.changue_role', user_id = user.id)}}" method="post">
          <p class="form-label">Selecciona el rol de {{user.name}}:</p>
          {%for role in roles:%}
          <input type="radio" id="color1" name="user_role" value="{{role.id}}" class="form-check-input">
          <label for="color1" class="form-check-label"> {{role.role_title}}</label><br>
          {%endfor%}
          
          <div class="mt-5">
            <input type="submit" value="Submit" class="btn btn-primary btn-md">
          </div>
      </form>      
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %} 

app/templates/footer.html
        <!-- Footer-->
        <footer class="border-top">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-md-10 col-lg-8 col-xl-7">
                 
                      <div class="small text-center text-muted fst-italic"></div>
                  </div>
              </div>
          </div>
      </footer>
      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
      <!-- Core theme JS-->
      <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
  </body>
</html>

app/templates/index.html
{% from "macros.html" import render_select_field %}   
{% from "bootstrap5/form.html" import render_form %} {% block content %} 
{% include "header.html" %}


<!-- Main Content-->
<div class="container px-4 px-lg-5 mt-5 pt-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!--TODO: remake render_form macro to make custome search layout and not send CSRF token -->
      <!-- {{render_form(filter_form, method='get')}} -->

      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <form class="d-flex" action="" method="get" role="form">
            
            {{ filter_form.folio(class="form-control me-2", placeholder = 'Folio') }}
            <!-- <input class="form-control me-2" type="search" placeholder="Folio" aria-label="Search" name="folio"> -->
            {{render_select_field(filter_form.document_type)}}
            {{render_select_field(filter_form.author)}}
            {{render_select_field(filter_form.tags)}}

            <button class="btn btn-primary" type="submit">Buscar</button>

          </form>
        </div>
      </nav>
      <hr class="my-4" />

      <!-- Post preview-->
      {% for post in all_posts %}

      <div class="post-preview">
        <a href="{{ url_for('bills.show', bill_id=post.id) }}">
          <h2 class="post-title">{{ post.name }}</h2>
          <h3 class="post-subtitle">{{ post.folio }}</h3>
          <h3 class="post-subtitle">{{ post.bill_concept }}</h3>
        </a>

        <p class="post-meta">
          Creado por <a href="#">{{post.author.name}}</a> el {{post.bill_date}}
        </p>
      </div>
      {%if current_user.role.can_delete_bills %}
      <a class="btn btn-danger" href="{{url_for('bills.delete_bill', bill_id=post.id) }}">Eliminar</a>
      {%endif%}
      <!-- Divider-->
      <hr class="my-4" />
      {% endfor %}

      <!-- New Post -->
      {%if current_user.role.can_create_bills %}
      <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-primary float-right" href="{{url_for('bills.add_new_bill')}}">Nuevo Documento</a>
      </div>
      {%endif%}

      <!-- Links to other pages -->
      <div class="d-flex justify-content-center my-4">
        {% if all_posts.has_prev %}
            <a class="btn btn-outline-primary mx-2" href="{{ url_for('bills.get_all', page=all_posts.prev_num) }}">
              <i class="fas fa-chevron-left"></i> Anterior
            </a>
        {% endif %}
        {% if all_posts.has_next %}
            <a class="btn btn-outline-primary mx-2" href="{{ url_for('bills.get_all', page=all_posts.next_num) }}">
              Siguiente <i class="fas fa-chevron-right"></i>
            </a>
        {% endif %}
      </div>

    </div>
  </div>
</div>



{% include "footer.html" %}{%endblock%}

app/templates/register.html
{% from "bootstrap5/form.html" import render_form %} {% block content %}
{%include "header.html" %}

<!-- Page Header -->
<!-- <header
  class="masthead"
  style="background-image: url('../static/assets/img/register-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Registrar</h1>
          <span class="subheading">Empieza a capturar tus datos!</span>
        </div>
      </div>
    </div>
  </div>
</header> -->

<main class="mb-4 mt-5 pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
              <p class="flash">{{ message }}</p>
            {% endfor %}
          {% endif %}
        {% endwith %}
        <form method="POST" action="{{url_for('auth.register')}}">
          {{ form.hidden_tag() }}

          <div class="form-group">
            <strong>
              {{ form.email.label(class="control-label") }}
            </strong>
            {{ form.email(class="form-control") }}
          </div>

          <div class="form-group">
            <strong>
              {{ form.name.label(class="control-label") }}
            </strong>
            {{ form.name(class="form-control") }}
          </div>

          <div class="form-group">
            <strong>
              {{ form.password.label(class="control-label") }}
            </strong>
            {{ form.password(class="form-control") }}
          </div>

          <div class="d-flex justify-content-start mt-3">
            {{ form.submit(class="btn btn-primary") }}
            <a href="{{url_for('auth.login')}}" class="btn btn-danger mx-3">Cancelar</a>
          </div>

        </form>

      </div>
    </div>
  </div>
</main>

{% include "footer.html" %} {% endblock %}

app/templates/roles.html
{% include "header.html" %}

<!-- Page Header-->
<!-- <header class="masthead" style="background-image: url('../static/assets/img/admin-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Administracion</h1>
          <span class="subheading">Panel de Administracion Roles.</span>
          
        </div>
      </div>
    </div>
  </div>
</header> -->

<div class="container px-4 px-lg-5 mt-5 pt-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <!-- Post preview-->
        {% for role in all_roles %}  
        <div class="post-preview">
          <a href="#">
            <h2 class="post-title">{{ role.role_title}}</h2>
            <h3 class="post-subtitle">{{ role.role_description }}</h3>
            <!-- <h3 class="post-subtitle" style = 'color:red;'>{{role.role_title}}</h3>   -->
          </a>
          <p class="post-meta">            
            {%if current_user.role.can_edit_roles%}    
            <a href="{{url_for('roles.edit_role', role_id = role.id)}}">Editar</a>
            {%endif%}

            {%if current_user.role.can_delete_roles and current_user.role != role %}
            <a href="{{url_for('roles.delete_role', role_id = role.id)}}">Eliminar</a>
            {%endif%}
          </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        {% endfor %}
        <!-- New Post -->
        {%if current_user.role.can_create_roles%}
        <div class="d-flex justify-content-end mb-4">
          <a class="btn btn-primary float-right" href="{{url_for('roles.create_role')}}">Crear nuevo rol</a>
        </div>
        {%endif%}
      </div>
    </div>
  </div>
  

{% include "footer.html" %}

app/templates/tag-manager.html
{% from "bootstrap5/form.html" import render_form %} {% block content %} 
{%include "header.html" %}

<!-- Page Header -->
<!-- <header
  class="masthead"
  style="background-image: url('../static/assets/img/register-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Registrar</h1>
          <span class="subheading">Empieza a capturar tus datos!</span>
        </div>
      </div>
    </div>
  </div>
</header> -->

<main class="mb-4 mt-5 pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
              <p class="flash">{{ message }}</p>
            {% endfor %}
          {% endif %}
        {% endwith %}

        {%if current_user.role.can_create_tags%}
        {{render_form(form)}}
        {%endif%}
        
        <hr class="my-4" />
        {% for item in items: %}
        <div class="post-preview">
          <a href="#">
            <h2 class="post-title">{{item.name}}</h2>
          </a>
          <p class="post-meta">            
            {%if current_user.role.can_delete_tags%}
            <a href="{{url_for('tags.delete', tag_id = item.id)}}">Eliminar</a>
            {%endif%}
          </p>
        </div>
        {%endfor %}
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %} {% endblock %}

app/templates/type-manager.html
{% from "bootstrap5/form.html" import render_form %} {% block content %} 
{%include "header.html" %}

<!-- Page Header -->
<!-- <header
  class="masthead"
  style="background-image: url('../static/assets/img/register-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Registrar</h1>
          <span class="subheading">Empieza a capturar tus datos!</span>
        </div>
      </div>
    </div>
  </div>
</header> -->

<main class="mb-4 mt-5 pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
              <p class="flash">{{ message }}</p>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {{render_form(form)}}
        <hr class="my-4" />
        {% for item in items: %}
        <div class="post-preview">

            <h2 class="post-title">{{item.name}}</h2>
          <p class="post-meta">            
            {%if current_user.role.can_manage_document_types %}
            <a href="{{url_for('doc_types.delete_document_type', type_id = item.id)}}">Eliminar</a>
            {%endif%}
          </p>
        </div>
        {%endfor %}
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %} {% endblock %}

app/templates/users.html
{% include "header.html" %}

<!-- Page Header-->
<!-- <header class="masthead" style="background-image: url('../static/assets/img/admin-bg.jpg')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Administracion</h1>
          <span class="subheading">Panel de Administracion Usuarios.</span>
          
        </div>
      </div>
    </div>
  </div>
</header> -->

<div class="container px-4 px-lg-5 mt-5 pt-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <p class="flash">{{ message }}</p>
          {% endfor %}
        {% endif %}
      {% endwith %}

        <!-- Post preview-->
        {% for user in all_users %}  
        <div class="post-preview">
          <a href="#">
            <h2 class="post-title">{{ user.name}}</h2>
            <h3 class="post-subtitle">{{ user.email }}</h3>
            <h3 class="post-subtitle" style = 'color:red;'>{{user.role.role_title}}</h3>  
          </a>
          <p class="post-meta">            
            {%if current_user.role.can_edit_users%}    
            <a href="{{url_for('users.edit_user', user_id = user.id)}}">Editar</a>
            <a href="{{url_for('users.changue_role', user_id = user.id)}}">Cambiar Rol</a>
            {%endif%}

            {%if current_user.role.can_delete_users and user != current_user%}
            <a href="{{url_for('users.delete_user', user_id = user.id)}}">Eliminar</a>
            {%endif%}

          </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        {% endfor %}
        <!-- New Post -->
        {%if current_user.role.can_create_users%}
        <div class="d-flex justify-content-end mb-4">
          <a class="btn btn-primary float-right" href="{{url_for('auth.register')}}">Crear nuevo usuario</a>
        </div>
        {%endif%}
      </div>
    </div>
  </div>
  

{% include "footer.html" %}